sudo: required
services:
  - docker

script:
  - docker build -t bhanuraina/node .
  - docker images bhanuraina/node    

before_deploy:
  - docker login -u bhanuraina -p james12#

deploy:
  provider: script
  script: docker push bhanuraina/node
  on:
    branch: master
